contact_links:
  - name: Discussions
    url: https://github.com/razonyang/hugo-theme-bootstrap/discussions/new
    about: Ask and discuss questions with others.
  - name: Documentations
    url: https://ingvdboom-notes.netlify.app
    about: Read and search the documentations.
